
previews:
  generation: automatic

services:
  # Main MERN Stack Application
  - type: web
    runtime: docker
    name: example-react-app
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    region: oregon
    numInstances: 1
    autoDeploy: true
    healthCheckPath: /health
    buildCommand: echo "Building with Docker..."
    startCommand: bun run --cwd server-ts start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: IS_SSR
        value: true
      - key: DATABASE_TYPE
        value: postgres
      - key: DATABASE_URL
        fromDatabase:
          name: example-postgres-db
          property: connectionString
      - key: POSTGRES_HOST
        fromDatabase:
          name: example-postgres-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: example-postgres-db
          property: port
      - key: POSTGRES_DATABASE
        fromDatabase:
          name: example-postgres-db
          property: database
      - key: POSTGRES_USERNAME
        fromDatabase:
          name: example-postgres-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: example-postgres-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 1h
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - fromGroup: app-config

databases:
  - name: elephant
    databaseName: mydb
    user: adrian
    ipAllowList:
      - source: 203.0.113.4/30
        description: office
      - source: 198.51.100.1
        description: home
    readReplicas:
      - name: elephant-replica

  - name: private database
    databaseName: private
    ipAllowList: []

  - name: pachyderm
    plan: basic-1gb
    diskSizeGB: 35

  - name: highly available database
    plan: pro-8gb
    highAvailability:
      enabled: true

envVarGroups:
  - name: conc-settings
    envVars:
      - key: CONCURRENCY
        value: 2
      - key: SECRET
        generateValue: true
  - name: stripe
    envVars:
      - key: STRIPE_API_URL
        value: https://api.stripe.com/v2