name: build-backend-heroku

on: [push]

jobs:
  auto-build-be:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: akhileshns/heroku-deploy@v3.0.0
      - name: remove node_modules
        run: cd ./server && rm -rf node-node_modules yarn.lock && yarn && heroku git:remote -a peanut-node && cd ..
      - uses: akhileshns/heroku-deploy@v3.0.0
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'peanut-node'
          heroku_email: 'truongdq.dev@gmail.com'
