name: build-backend-heroku

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: |
          git fetch --prune --unshallow

      - uses: actions/setup-node@v3
        with:
          node-version: '14.17.1'
      
      - name: Install heroku cli
        run: |
          npm install -g heroku

      - name: Check version heroku cli
        run: | 
          heroku --version

      - name: Navigate to server folder
        run: |
          cd ./server          

      - name: Add remote origin
        if: github.ref == 'refs/heads/master' && job.status == 'success' #we specify that this action will ONLY run if everything up to now is successful- so if theres a fail in the tests, then this will not be deployed.
        run: |
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/peanut-node.git

      - name: Add build pack
        run: | 
          heroku buildpacks:set https://github.com/heroku/heroku-buildpack-nodejs#latest -a peanut-node

      - name: Deploy to Heroku
        run: |
          git push heroku HEAD:master -f
