name: build-backend-heroku

on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
      - name: remove node_modules
        run: cd ./server && rm -rf node-node_modules yarn.lock && yarn && cd ..
      - name: deployment BE heroku
        uses: ./
        with:
          node-version: '16.14.2'
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'peanut-node'
          heroku_email: 'truongdq.dev@gmail.com'
