name: build-backend-heroku

on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.14.2'
      - name: Add remote to heroku platform.
        if: github.ref == 'ref/heads/master' && jobs.status == 'success'
        run: |
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/peanut-node.git
      - name: Deployment backend to heroku platform.
        run: |
          git push heroku HEAD:master -f
